path: C:\Users\domin\OneDrive\Pulpit\PWR\RIPO\RIPO\data  # dataset root dir
train: train\images  # train images (relative to 'path')
val: train\images  # val images (relative to 'path')

# Classes
names:
  0: stop_sign
  1: red_light
  2: green_light
  3: yellow_light